# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "sizeofvoid case"
license = "MIT"
licenselink = "https://github.com/ExchangeRate-API/sizeofvoid-case/LICENSE.md"
description = "A 2 column blog theme for Hugo using Bootstrap - inspired by the strange-case theme by ExchangeRate-API"
homepage = "https://github.com/ExchangeRate-API/sizeofvoid-case"
tags = ["", ""]
features = ["", ""]
min_version = 0.16

[author]
	name = "Rafael Sadowski <rafael@sizeofvoid.org>"
	homepage = "https://www.sizeofvoid.org/"

# If porting an existing theme
[original]
	name = "ExchangeRate-API"
	homepage = "https://www.exchangerate-api.com"
	repo = "https://github.com/ExchangeRate-API/strange-case"
